title: Jekyll blog test on jamesbungay.github.io
author: James Bungay
email: jtb.github@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Testing a Jekyll blog to see if static site generators are useful or not for the modern web.

# social links
twitter_username: ja_me_s_ # DO NOT include the @ character, or else the build will fail!
github_username:  jamesbungay # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
